In [1]:
import json
import pandas as pd

In [2]:
# Load the JSON dataset
with open("Original Datasets/intents.json", "r") as file:
    data = json.load(file)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
rows = []

for intent in data["intents"]:
    tag = intent["tag"]

    for pattern in intent["patterns"]:
        rows.append({
            "tag": tag,
            "pattern": pattern,
            "response": intent["responses"][0]
        })

df = pd.DataFrame(rows)

df.head()

,tag,pattern,response
0,greeting,Hi,Hello! How can I assist you with Medical Assis...
1,greeting,Hello,Hello! How can I assist you with Medical Assis...
2,greeting,Hey,Hello! How can I assist you with Medical Assis...
3,greeting,Greetings,Hello! How can I assist you with Medical Assis...
4,cancer_general,What is cancer?,Cancer is a group of diseases characterized by...

In [4]:
print("Final Dataset Shape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Information:")
df.info()

Final Dataset Shape:
(98, 3)

Columns:
['tag', 'pattern', 'response']

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tag       98 non-null     object
 1   pattern   98 non-null     object
 2   response  98 non-null     object
dtypes: object(3)
memory usage: 2.4+ KB

In [5]:
print("Missing Values:")
display(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Missing Values:

tag         0
pattern     0
response    0
dtype: int64

Duplicate Rows:
0

In [7]:
# Number of words in each user query
df["pattern_length"] = df["pattern"].apply(lambda x: len(x.split()))

# Number of words in chatbot response
df["response_length"] = df["response"].apply(lambda x: len(x.split()))

df.head()

,tag,pattern,response,pattern_length,response_length
0,greeting,Hi,Hello! How can I assist you with Medical Assis...,1,10
1,greeting,Hello,Hello! How can I assist you with Medical Assis...,1,10
2,greeting,Hey,Hello! How can I assist you with Medical Assis...,1,10
3,greeting,Greetings,Hello! How can I assist you with Medical Assis...,1,10
4,cancer_general,What is cancer?,Cancer is a group of diseases characterized by...,3,40

In [8]:
df.describe(include="all")

,tag,pattern,response,pattern_length,response_length
count,98,98,98,98.000000,98.000000
unique,22,98,22,NaN,NaN
top,alzheimers_symptoms,Hi,It seems like you may be experiencing symptoms...,NaN,NaN
freq,5,1,5,NaN,NaN
mean,NaN,NaN,NaN,8.122449,43.561224
std,NaN,NaN,NaN,6.498636,24.176783
min,NaN,NaN,NaN,1.000000,10.000000
25%,NaN,NaN,NaN,4.000000,25.750000
50%,NaN,NaN,NaN,6.000000,35.000000
75%,NaN,NaN,NaN,10.000000,67.750000
max,NaN,NaN,NaN,29.000000,87.000000

In [9]:
df.to_csv("Processed Datasets/processed_data.csv", index=False)

columns = pd.DataFrame(df.columns, columns=["Column_Name"])
columns.to_csv(
    "Processed Datasets/processed_data_columns.csv",
    index=False
)

print("Processed files saved successfully!")

Processed files saved successfully!

In [10]:
processed_df = pd.read_csv("Processed Datasets/processed_data.csv")
processed_df.head()

,tag,pattern,response,pattern_length,response_length
0,greeting,Hi,Hello! How can I assist you with Medical Assis...,1,10
1,greeting,Hello,Hello! How can I assist you with Medical Assis...,1,10
2,greeting,Hey,Hello! How can I assist you with Medical Assis...,1,10
3,greeting,Greetings,Hello! How can I assist you with Medical Assis...,1,10
4,cancer_general,What is cancer?,Cancer is a group of diseases characterized by...,3,40